name: idk
on: push
permissions:
  contents: write
jobs:
  ever:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: tag_push
        uses: actions/github-script@v6
        with:
          script: |
            const version_type = 'major'
            const major = '1'
            const minor = '1'
            const patch = '0'
