name: idk
on: push
permissions:
  contents: write
jobs:
  ever:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Release generation
        id: release_generation
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v1.1.0
          files: README.md