name: idk
on: push
permissions:
  contents: write
jobs:
  ever:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: tag_push
        uses: actions/github-script@v6
        with:
          script: |
            const version_type = 'major'
            const major = '1'
            const minor = '1'
            const patch = '0'

            const response = await github.rest.git.createRef({
              owner: context.repo.owner
              repo: context.repo.repo
              ref: `$refs/tags/${major}.${minor}.${patch}`
            })

            console.log(JSON.stringify(response));


      - name: Release generation
        id: release_generation
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v1.1.0
          files: README.md
          target_commitish: ${{ github.sha }}